@extends('layouts.app')
@section('title', $group->name ?: '移行 #'.$group->id)
@section('content')
<div class="crumb"><a href="{{ route('transfers.index') }}">ポイント・マイル移行</a> / 詳細</div>
<div class="page-head"><div><h1>{{ $group->name ?: '移行 #'.$group->id }}</h1><p class="muted">{{ $group->purpose ?: '目的未設定' }} · {{ ['planned'=>'予定','processing'=>'処理中','completed'=>'完了','cancelled'=>'取消','error'=>'エラー'][$group->status] ?? $group->status }}</p></div>@if(!in_array($group->status, ['completed','cancelled','error']))<a class="button secondary" href="{{ route('transfers.steps.create', $group) }}">ステップを追加</a>@endif</div>
<div class="card"><dl class="detail-grid"><div><dt>名義</dt><dd>{{ $group->householdMember?->display_name ?? '家族共通・未設定' }}</dd></div><div><dt>最終目的制度</dt><dd>{{ $group->targetProgram?->name ?? '未設定' }}</dd></div><div><dt>目標数量</dt><dd>{{ $group->target_quantity ?? '未設定' }} {{ $group->targetProgram?->unit_name }}</dd></div><div><dt>進捗</dt><dd>{{ $steps->where('status','completed')->count() }} / {{ $steps->count() }} 完了</dd></div><div><dt>開始日</dt><dd>{{ $group->started_at ?: '—' }}</dd></div><div><dt>全体着弾予定</dt><dd>{{ $group->expected_complete_at ?: '—' }}</dd></div><div><dt>完了日</dt><dd>{{ $group->completed_at ?: '—' }}</dd></div></dl>@if($group->memo)<p>{{ $group->memo }}</p>@endif</div>
@forelse($steps as $step)
@php($overdue = $step->status === 'processing' && $step->expected_complete_at && $step->expected_complete_at < now('Asia/Tokyo')->toDateString())
<section class="card"><div class="page-head"><div><h2>Step {{ $step->sequence_no }} · {{ $step->fromAccount->program->name }} → {{ $step->toAccount->program->name }}</h2><p class="muted">{{ ['planned'=>'予定','processing'=>'処理中','completed'=>'完了','cancelled'=>'取消','error'=>'エラー'][$step->status] ?? $step->status }} @if($overdue) · <strong>予定日超過</strong>@endif</p></div>@if(in_array($step->status, ['processing','error']))<a class="button" href="{{ route('transfers.steps.complete.form', $step) }}">着弾した</a>@endif</div>
<dl class="detail-grid"><div><dt>移行元の申請数量</dt><dd>{{ $step->source_quantity }} {{ $step->fromAccount->program->unit_name }}</dd></div><div><dt>移行先の受取予定</dt><dd>{{ $step->expected_destination_quantity ?? '未設定' }} {{ $step->toAccount->program->unit_name }}</dd></div><div><dt>実際の受取数量</dt><dd>{{ $step->actual_destination_quantity ?? '—' }} {{ $step->actual_destination_quantity !== null ? $step->toAccount->program->unit_name : '' }}</dd></div>@if($step->actual_destination_quantity !== null && $step->expected_destination_quantity !== null)<div><dt>予定との差異</dt><dd>{{ \Brick\Math\BigDecimal::of($step->actual_destination_quantity)->minus($step->expected_destination_quantity) }} {{ $step->toAccount->program->unit_name }}</dd></div>@endif<div><dt>最終換算</dt><dd>{{ $step->planning_equivalent_quantity ?? '—' }} {{ $step->planningEquivalentProgram?->unit_name }}</dd></div><div><dt>申請日</dt><dd>{{ $step->started_at ?: '—' }}</dd></div><div><dt>着弾予定日</dt><dd>{{ $step->expected_complete_at ?: '—' }}</dd></div><div><dt>完了日</dt><dd>{{ $step->completed_at ?: '—' }}</dd></div></dl>
@if($overdue)<p class="warning">着弾予定日を過ぎています。移行先の残高を確認してください。</p>@elseif($step->status === 'processing' && $step->expected_complete_at && $step->expected_complete_at <= now('Asia/Tokyo')->addDays(3)->toDateString())<p class="help">まもなく着弾予定です。移行先の残高を確認してください。</p>@elseif($step->status === 'processing')<p class="help">移行先への着弾待ちです。</p>@elseif($step->status === 'completed' && $steps->firstWhere('sequence_no', $step->sequence_no + 1)?->status === 'planned')<p class="help">次のステップを申請できます。</p>@endif
@if($step->conversionRule)<p class="muted">交換ルール #{{ $step->conversionRule->id }} を使用。受取予定数量は計画作成時の値です。</p>@endif
@if($step->memo)<p>{{ $step->memo }}</p>@endif
@if($step->status === 'planned')<form class="row" method="post" action="{{ route('transfers.steps.start', $step) }}">@csrf<div class="field"><label for="started-{{ $step->id }}">申請日</label><input id="started-{{ $step->id }}" type="date" name="started_at" value="{{ now('Asia/Tokyo')->toDateString() }}" required></div><button>申請した</button></form><form method="post" action="{{ route('transfers.steps.cancel', $step) }}" onsubmit="return confirm('この計画ステップを取り消しますか？')">@csrf<button class="danger">計画を取り消す</button></form>@endif
@if(in_array($step->status, ['planned','processing']))<form class="row" method="post" action="{{ route('transfers.steps.expected-date', $step) }}">@csrf<div class="field"><label for="expected-{{ $step->id }}">着弾予定日を変更</label><input id="expected-{{ $step->id }}" name="expected_complete_at" type="date" value="{{ $step->expected_complete_at }}" required></div><div class="field"><label for="date-memo-{{ $step->id }}">変更理由</label><input id="date-memo-{{ $step->id }}" name="memo"></div><button class="secondary">予定日を保存</button></form>@endif
@if($step->status === 'processing')<form class="row" method="post" action="{{ route('transfers.steps.error', $step) }}" onsubmit="return confirm('エラーとして記録しますか？ 残高は自動で戻りません。')">@csrf<div class="field"><label for="error-memo-{{ $step->id }}">エラーの理由</label><input id="error-memo-{{ $step->id }}" name="memo" required></div><button class="secondary">エラーとして記録</button></form>@endif
@if(in_array($step->status, ['processing','error']))<form class="row" method="post" action="{{ route('transfers.steps.refund', $step) }}" onsubmit="return confirm('外部申請が取消され、元のポイントが実際に返還されたことを確認しましたか？')">@csrf<div class="field"><label for="refund-memo-{{ $step->id }}">返還の理由</label><input id="refund-memo-{{ $step->id }}" name="memo" required></div><button class="danger">返還を記録して取消</button></form>@endif
</section>
@empty<div class="card"><p>ステップがありません。</p><a class="button" href="{{ route('transfers.steps.create', $group) }}">最初のステップを追加</a></div>@endforelse
@endsection
