@extends('layouts.app')
@section('title', $listing->title ?: '出品 #'.$listing->id)
@section('content')
<div class="crumb"><a href="{{ route('listings.index') }}">出品・売却</a> / 詳細</div>
<div class="page-head"><div><h1>{{ $listing->title ?: '出品 #'.$listing->id }}</h1><p class="muted">{{ $listing->marketplace }} · {{ ['draft'=>'下書き','listed'=>'出品中','sold'=>'売却済み','ended_unsold'=>'売れず終了','cancelled'=>'取消'][$listing->status] ?? $listing->status }} @if($listing->sale_reversed_at) · 売却取消済み @endif</p></div><div class="row">@if(in_array($listing->status, ['draft','listed']))<a class="button secondary" href="{{ route('listings.edit', $listing) }}">編集</a>@endif @if($listing->status === 'listed')<a class="button" href="{{ route('listings.sell.form', $listing) }}">売れた</a>@endif</div></div>
<div class="card"><h2>出品内容</h2><dl class="detail-grid"><div><dt>現在価格</dt><dd>{{ $listing->listing_price_yen === null ? '未設定' : number_format($listing->listing_price_yen).' 円' }}</dd></div><div><dt>受け渡し</dt><dd>{{ ['digital'=>'電子コード','shipping'=>'郵送','handoff'=>'手渡し','other'=>'その他'][$listing->delivery_type] ?? '未設定' }}</dd></div><div><dt>出品日</dt><dd>{{ $listing->listed_at ?: '—' }}</dd></div><div><dt>終了日</dt><dd>{{ $listing->ended_at ?: '—' }}</dd></div>@if($listing->status === 'sold')<div><dt>売却日</dt><dd>{{ $listing->sold_at }}</dd></div><div><dt>売却額</dt><dd>{{ number_format($listing->sold_price_yen) }} 円</dd></div><div><dt>手数料</dt><dd>{{ number_format($listing->fee_yen) }} 円</dd></div><div><dt>送料</dt><dd>{{ number_format($listing->shipping_yen) }} 円</dd></div><div><dt>手取り</dt><dd>{{ number_format($listing->net_proceeds_yen) }} 円</dd></div>@endif</dl>@if($listing->status === 'sold' && $listing->net_proceeds_yen < 0)<p class="warning">手数料と送料が売却価格を上回っています。</p>@endif @if($listing->listing_url)<p><a href="{{ $listing->listing_url }}" target="_blank" rel="noopener noreferrer">外部の出品ページを開く</a></p>@endif @if($listing->memo)<p>{{ $listing->memo }}</p>@endif</div>
<div class="card"><h2>対象特典</h2><div class="list">@foreach($listing->items as $item)<div class="list-item"><div><a href="{{ route('ledger.lots.show', $item->lot) }}">{{ $item->lot->display_name ?: $item->lot->account->program->name }}</a><small>期限 {{ $item->lot->expires_at ?: 'なし' }} · {{ $item->lot->account->householdMember?->display_name ?? '家族共通' }}</small></div><strong>{{ $item->quantity }} {{ $item->lot->account->program->unit_name }}</strong></div>@endforeach</div></div>
@if($listing->status === 'draft')<div class="card"><h2>出品開始</h2><form class="stack" method="post" action="{{ route('listings.publish', $listing) }}">@csrf<label><input type="checkbox" name="confirm_policy" value="1"> 「今売る／セット販売」以外の方針も確認した</label><label><input type="checkbox" name="confirm_mixed_expiry" value="1"> 異なる期限を含む場合、購入者への表示を確認した</label><button type="submit">出品中にする</button></form></div>@endif
@if($listing->status === 'listed')<div class="card"><h2>価格を変更</h2><form class="row" method="post" action="{{ route('listings.price', $listing) }}">@csrf<div class="field"><label for="new_price">新価格（円）</label><input id="new_price" name="listing_price_yen" type="number" min="0" value="{{ $listing->listing_price_yen }}" required></div><div class="field"><label for="reason">理由</label><input id="reason" name="reason" maxlength="255"></div><button type="submit">価格を保存</button></form></div>@endif
@if(in_array($listing->status, ['draft','listed']))<div class="card"><h2>出品を終了</h2><div class="row">@if($listing->status === 'listed')<form method="post" action="{{ route('listings.end-unsold', $listing) }}" onsubmit="return confirm('売れず終了として記録しますか？')">@csrf<button class="secondary">売れず終了</button></form>@endif<form method="post" action="{{ route('listings.cancel', $listing) }}" onsubmit="return confirm('出品を取り下げますか？')">@csrf<button class="danger">取り下げ</button></form></div></div>@endif
@if(in_array($listing->status, ['cancelled','ended_unsold']) || ($listing->status === 'sold' && $listing->sale_reversed_at))<div class="card"><form method="post" action="{{ route('listings.relist', $listing) }}">@csrf<button>新しい下書きとして再出品</button></form></div>@endif
@if($listing->status === 'sold' && !$listing->sale_reversed_at)<div class="card"><h2>売却訂正</h2><form method="post" action="{{ route('listings.reverse-sale', $listing) }}" onsubmit="return confirm('売却を取り消して在庫を戻しますか？')">@csrf<button class="danger">売却を取り消す</button></form></div>@endif
<div class="card"><h2>価格履歴</h2><div class="list">@forelse($listing->priceHistory->sortBy('id') as $history)<div class="list-item"><span>{{ $history->changed_at }} · {{ $history->reason ?: '価格設定' }}</span><strong>{{ number_format($history->price_yen) }} 円</strong></div>@empty<p>価格履歴はありません。</p>@endforelse</div></div>
@endsection
