@extends('layouts.app')
@section('title', 'Excel取込プレビュー')
@section('content')
<div class="crumb"><a href="{{ route('imports.index') }}">Excel取込</a> / #{{ $batch->id }}</div>
<h1>取込プレビュー</h1>
@php($statusLabels = ['pending'=>'解析済み','ready'=>'取込可能','warning'=>'要確認','needs_review'=>'要確認','imported'=>'取込済み','skipped_duplicate'=>'重複','skipped_out_of_scope'=>'対象外','error'=>'エラー'])
@php($warningLabels = ['mapping_required'=>'明示マッピングが必要です','unsupported_headers'=>'列定義を確認できません','native_quantity_missing'=>'native数量を明示補正してください','native_quantity_unconfirmed'=>'数量の単位を確認してください','invalid_native_quantity'=>'数量の範囲・小数桁を確認してください','status_unconfirmed'=>'移行状態を確認してください','invalid_status_dates'=>'状態と申請・完了日が一致していません','invalid_date'=>'日付を明示補正してください','actual_quantity_unconfirmed'=>'実着弾数量を確認してください','equivalent_program_unresolved'=>'換算数量の制度を選択してください','history_link_unresolved'=>'既存取引の口座・数量・日付・紐づけ状況を確認してください','unexpected_history_link'=>'この状態では指定した取引を紐づけられません','program_unresolved'=>'元・先の制度名やaliasを確認してください','account_unresolved'=>'有効な元・先口座を選択してください','rule_group_mismatch'=>'ルール系列の元・先制度が一致していません','campaign_unconfirmed'=>'キャンペーン限定の条件を確認してください','campaign_period_unresolved'=>'キャンペーン期間を確認してください','invalid_duration'=>'所要日数の範囲を確認してください','commit_failed'=>'登録できませんでした。行を再確認してください','duplicate'=>'この取込先には登録済みです'])
<div class="card"><p><strong>{{ $batch->source_filename }}</strong> · {{ $batch->status }} · {{ $batch->importer_version }}</p><p>SHA-256: <code>{{ $batch->file_checksum }}</code></p><p>対象 {{ $batch->total_rows }} / 取込済み {{ $batch->imported_rows }} / スキップ {{ $batch->skipped_rows }} / 要確認 {{ $batch->warning_rows }} / エラー {{ $batch->error_rows }}</p>@if($alreadyUploaded)<p class="warning">同一ファイルの解析履歴があります。口座を選択すると、その口座への取込済み行を重複判定します。</p>@endif</div>
@if(in_array($batch->status, ['preview', 'completed_with_errors']))
<form class="card" method="post" action="{{ route('imports.configure', $batch) }}">@csrf<h2>シート別マッピング</h2><p class="muted">口座と名義を確認してください。移行・交換は数量と状態を明示確認し、未解決行と商品券は要確認のまま保持します。</p>
@foreach($sheets as $sheet)
<fieldset class="import-sheet"><legend>{{ $sheet }}</legend>
 <div class="field"><label for="action_{{ $loop->index }}">取込方針</label><select id="action_{{ $loop->index }}" name="mappings[{{ $sheet }}][action]"><option value="import">対象行を取込候補にする</option><option value="skip">対象外としてスキップ</option></select></div>
 @if(in_array($sheetTypes[$sheet] ?? null, ['transfer', 'conversion_rule']))
 @include('imports.mapped-fields', ['type'=>$sheetTypes[$sheet], 'prefix'=>'mappings['.$sheet.']', 'record'=>null])
 @else
 <div class="field"><label for="account_{{ $loop->index }}">既存口座</label><select id="account_{{ $loop->index }}" name="mappings[{{ $sheet }}][account_id]"><option value="">選択してください</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->householdMember?->display_name }} / {{ $account->program->name }} / {{ $account->account_label }}</option>@endforeach</select></div>
 <p class="muted">既存口座がない場合は以下を指定します。プレビューでは作成せず、取込実行時に作成します。</p>
 <label><input type="checkbox" name="mappings[{{ $sheet }}][create_account]" value="1"> 新規口座を作成予定にする</label>
 <div class="field"><label for="new_program_{{ $loop->index }}">新規口座の制度</label><select id="new_program_{{ $loop->index }}" name="mappings[{{ $sheet }}][new_program_id]"><option value="">選択</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></div>
 <div class="field"><label for="new_member_{{ $loop->index }}">新規口座の名義</label><select id="new_member_{{ $loop->index }}" name="mappings[{{ $sheet }}][new_member_id]"><option value="">家族共通</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->display_name }}</option>@endforeach</select></div>
 <div class="field"><label for="new_label_{{ $loop->index }}">新規口座のラベル</label><input id="new_label_{{ $loop->index }}" name="mappings[{{ $sheet }}][new_label]" maxlength="150"></div>
 @if(in_array($sheet, ['ポイント積立', 'ポイント利用']))<label><input type="checkbox" name="mappings[{{ $sheet }}][confirm_native]" value="1"> 履歴列の数量が選択した口座の native 数量であることを確認した</label>@endif
 @endif
</fieldset>
@endforeach
<button>マッピングを反映</button></form>
<form class="card" method="post" action="{{ route('imports.execute', $batch) }}">@csrf<h2>取込を実行</h2><p class="warning">「ready」の行だけ業務台帳へ追加します。残高不一致の行がある場合は内容を確認してください。</p><label><input type="checkbox" name="confirm_mismatch" value="1"> 残高不一致を確認した</label><p><button>取込を実行</button></p></form>
@endif
<div class="card"><h2>行別結果</h2><div class="list">@forelse($records as $record)<div class="list-item"><div><strong>{{ $record->source_sheet }} / 行 {{ $record->source_row_number }}</strong><small>{{ $statusLabels[$record->import_status] ?? $record->import_status }} ({{ $record->import_status }}) · {{ $warningLabels[$record->warning_code] ?? $record->warning_code ?: '警告なし' }}</small>@if($record->record_type === 'transaction' && $record->normalized_data_json)<small>{{ $record->normalized_data_json['date'] ?? '' }} · {{ $record->normalized_data_json['type'] ?? '' }} · {{ $record->normalized_data_json['quantity'] ?? '' }}@if(!empty($record->normalized_data_json['account_plan'])) · 新規口座作成予定: {{ $record->normalized_data_json['account_plan']['label'] ?: 'ラベルなし' }}@endif</small>@endif @if($record->error_message)<small>{{ $record->error_message }}</small>@endif</div>@if($record->target_id)<a href="{{ match($record->target_table) {'benefit_transfer_groups'=>route('transfers.show', $record->target_id), 'conversion_rules'=>route('conversion.rules.show', $record->target_id), default=>route('ledger.transactions.show', $record->target_id)} }}">登録内容を見る</a>@elseif(in_array($record->record_type, ['transfer', 'conversion_rule']) && in_array($batch->status, ['preview', 'completed_with_errors']))
<details class="import-row-edit"><summary>移行・交換ルールの行を確認・修正</summary>
@php($rawLabels = ['from_program'=>'元の制度','to_program'=>'先の制度','source_quantity'=>'元のnative数量','source_equivalent'=>'ポイント相当（参考）','planning_equivalent_quantity'=>'計画用の換算数量','expected_destination_quantity'=>'先のnative予定数量','actual_destination_quantity'=>'着弾したnative数量','started_at'=>'申請日','expected_complete_at'=>'完了予定日','completed_at'=>'完了日','status'=>'元の状態','from_quantity'=>'交換元数量','to_quantity'=>'交換先数量','minimum_from_quantity'=>'交換下限','effective_rate'=>'実質レート（参考）','conditions_text'=>'条件','instructions'=>'手順','duration_text'=>'所要時間','campaign_only'=>'キャンペーン限定','campaign_name'=>'キャンペーン名','valid_from'=>'有効開始日','valid_to'=>'有効終了日','name'=>'目的'])
<dl>@foreach($record->raw_data_json as $field => $value)<dt>{{ $rawLabels[$field] ?? '参考値' }}</dt><dd>{{ $value }}</dd>@endforeach</dl>
@include('imports.mapped-preview', ['record'=>$record])
<form class="stack" method="post" action="{{ route('imports.records.override', [$batch, $record]) }}">@csrf
<div class="field"><label>行の方針<select name="action"><option value="import">取込候補にする</option><option value="skip" @selected($record->import_status === 'skipped_out_of_scope')>スキップ</option></select></label></div>
@include('imports.mapped-fields', ['type'=>$record->record_type, 'prefix'=>'row', 'record'=>$record])
<button class="secondary">行を更新</button></form></details>
@elseif($record->record_type === 'transaction' && $record->import_status !== 'imported' && in_array($batch->status, ['preview', 'completed_with_errors']))<form method="post" action="{{ route('imports.records.override', [$batch, $record]) }}">@csrf<label for="row_action_{{ $record->id }}">方針</label><select id="row_action_{{ $record->id }}" name="action"><option value="import">取込</option><option value="skip">スキップ</option></select><label for="row_account_{{ $record->id }}">口座</label><select id="row_account_{{ $record->id }}" name="account_id"><option value="">選択</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($record->normalized_data_json['account_id'] ?? null) == $account->id)>{{ $account->householdMember?->display_name }} / {{ $account->program->name }} / {{ $account->account_label }}</option>@endforeach</select><label for="row_date_{{ $record->id }}">日付補正</label><input id="row_date_{{ $record->id }}" name="date_override" type="date" value="{{ $record->normalized_data_json['date_override'] ?? '' }}"><label for="row_quantity_{{ $record->id }}">数量補正（増加は正、減少は負）</label><input id="row_quantity_{{ $record->id }}" name="quantity_override" type="number" step="0.0001" value="{{ $record->normalized_data_json['quantity_override'] ?? '' }}"><label for="row_type_{{ $record->id }}">取引種別</label><select id="row_type_{{ $record->id }}" name="transaction_type"><option value="">自動判定</option>@foreach(['opening_balance'=>'初期残高','earn'=>'獲得','use'=>'利用'] as $type => $label)<option value="{{ $type }}" @selected(($record->normalized_data_json['type'] ?? '') === $type)>{{ $label }}</option>@endforeach</select><button class="secondary">行を更新</button></form>@endif</div>@empty<p>対象行はありません。</p>@endforelse</div>{{ $records->links() }}</div>
@endsection
