@extends('layouts.app')
@section('title', 'Excel取込プレビュー')
@section('content')
<div class="crumb"><a href="{{ route('imports.index') }}">Excel取込</a> / #{{ $batch->id }}</div>
<h1>取込プレビュー</h1>
<div class="card"><p><strong>{{ $batch->source_filename }}</strong> · {{ $batch->status }} · {{ $batch->importer_version }}</p><p>SHA-256: <code>{{ $batch->file_checksum }}</code></p><p>対象 {{ $batch->total_rows }} / 取込済み {{ $batch->imported_rows }} / スキップ {{ $batch->skipped_rows }} / 要確認 {{ $batch->warning_rows }} / エラー {{ $batch->error_rows }}</p>@if($alreadyUploaded)<p class="warning">同一ファイルの解析履歴があります。口座を選択すると、その口座への取込済み行を重複判定します。</p>@endif</div>
@if(in_array($batch->status, ['preview', 'completed_with_errors']))
<form class="card" method="post" action="{{ route('imports.configure', $batch) }}">@csrf<h2>シート別マッピング</h2><p class="muted">口座と名義を確認してください。移行・交換・商品券など自動判定できないシートは要確認のまま保持されます。</p>
@foreach($sheets as $sheet)
<fieldset><legend>{{ $sheet }}</legend>
 <div class="field"><label for="action_{{ $loop->index }}">取込方針</label><select id="action_{{ $loop->index }}" name="mappings[{{ $sheet }}][action]"><option value="import">対象行を取込候補にする</option><option value="skip">対象外としてスキップ</option></select></div>
 <div class="field"><label for="account_{{ $loop->index }}">既存口座</label><select id="account_{{ $loop->index }}" name="mappings[{{ $sheet }}][account_id]"><option value="">選択してください</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->householdMember?->display_name }} / {{ $account->program->name }} / {{ $account->account_label }}</option>@endforeach</select></div>
 <p class="muted">既存口座がない場合は以下を指定します。プレビューでは作成せず、取込実行時に作成します。</p>
 <label><input type="checkbox" name="mappings[{{ $sheet }}][create_account]" value="1"> 新規口座を作成予定にする</label>
 <div class="field"><label for="new_program_{{ $loop->index }}">新規口座の制度</label><select id="new_program_{{ $loop->index }}" name="mappings[{{ $sheet }}][new_program_id]"><option value="">選択</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></div>
 <div class="field"><label for="new_member_{{ $loop->index }}">新規口座の名義</label><select id="new_member_{{ $loop->index }}" name="mappings[{{ $sheet }}][new_member_id]"><option value="">家族共通</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->display_name }}</option>@endforeach</select></div>
 <div class="field"><label for="new_label_{{ $loop->index }}">新規口座のラベル</label><input id="new_label_{{ $loop->index }}" name="mappings[{{ $sheet }}][new_label]" maxlength="150"></div>
 @if(in_array($sheet, ['ポイント積立', 'ポイント利用']))<label><input type="checkbox" name="mappings[{{ $sheet }}][confirm_native]" value="1"> 履歴列の数量が選択した口座の native 数量であることを確認した</label>@endif
</fieldset>
@endforeach
<button>マッピングを反映</button></form>
<form class="card" method="post" action="{{ route('imports.execute', $batch) }}">@csrf<h2>取込を実行</h2><p class="warning">「ready」の行だけ業務台帳へ追加します。残高不一致の行がある場合は内容を確認してください。</p><label><input type="checkbox" name="confirm_mismatch" value="1"> 残高不一致を確認した</label><p><button>取込を実行</button></p></form>
@endif
<div class="card"><h2>行別結果</h2><div class="list">@forelse($records as $record)<div class="list-item"><div><strong>{{ $record->source_sheet }} / 行 {{ $record->source_row_number }}</strong><small>{{ $record->import_status }} · {{ $record->warning_code ?: '警告なし' }}</small>@if($record->normalized_data_json)<small>{{ $record->normalized_data_json['date'] ?? '' }} · {{ $record->normalized_data_json['type'] ?? '' }} · {{ $record->normalized_data_json['quantity'] ?? '' }}@if(!empty($record->normalized_data_json['account_plan'])) · 新規口座作成予定: {{ $record->normalized_data_json['account_plan']['label'] ?: 'ラベルなし' }}@endif</small>@endif @if($record->error_message)<small>{{ $record->error_message }}</small>@endif</div>@if($record->target_id)<a href="{{ route('ledger.transactions.show', $record->target_id) }}">取引を見る</a>@elseif($record->record_type === 'transaction' && $record->import_status !== 'imported' && in_array($batch->status, ['preview', 'completed_with_errors']))<form method="post" action="{{ route('imports.records.override', [$batch, $record]) }}">@csrf<label for="row_action_{{ $record->id }}">方針</label><select id="row_action_{{ $record->id }}" name="action"><option value="import">取込</option><option value="skip">スキップ</option></select><label for="row_account_{{ $record->id }}">口座</label><select id="row_account_{{ $record->id }}" name="account_id"><option value="">選択</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($record->normalized_data_json['account_id'] ?? null) == $account->id)>{{ $account->householdMember?->display_name }} / {{ $account->program->name }} / {{ $account->account_label }}</option>@endforeach</select><label for="row_date_{{ $record->id }}">日付補正</label><input id="row_date_{{ $record->id }}" name="date_override" type="date" value="{{ $record->normalized_data_json['date_override'] ?? '' }}"><label for="row_quantity_{{ $record->id }}">数量補正（増加は正、減少は負）</label><input id="row_quantity_{{ $record->id }}" name="quantity_override" type="number" step="0.0001" value="{{ $record->normalized_data_json['quantity_override'] ?? '' }}"><label for="row_type_{{ $record->id }}">取引種別</label><select id="row_type_{{ $record->id }}" name="transaction_type"><option value="">自動判定</option>@foreach(['opening_balance'=>'初期残高','earn'=>'獲得','use'=>'利用'] as $type => $label)<option value="{{ $type }}" @selected(($record->normalized_data_json['type'] ?? '') === $type)>{{ $label }}</option>@endforeach</select><button class="secondary">行を更新</button></form>@endif</div>@empty<p>対象行はありません。</p>@endforelse</div>{{ $records->links() }}</div>
@endsection
