@extends('layouts.app')
@section('title', $base->exists ? '新しいルール版' : '交換ルールを登録')
@section('content')
<div class="crumb"><a href="{{ route('conversion.rules.index') }}">交換ルール</a> / {{ $base->exists ? '新しい版' : '作成' }}</div><h1>{{ $base->exists ? '新しいバージョンを作成' : '交換ルールを登録' }}</h1>
@if($base->exists)<p class="help">Version {{ $base->version_no }} を複製します。経済条件を変更しても過去の移行には反映されません。</p>@endif
<form class="stack" method="post" action="{{ $base->exists ? route('conversion.rules.versions.store', $base) : route('conversion.rules.store') }}">@csrf
<div class="card"><h2>交換関係</h2>@if($base->exists)<p>{{ $base->group->fromProgram->name }} → {{ $base->group->toProgram->name }}</p>@else<div class="form-grid"><div class="field"><label for="from_program_id">交換元制度</label><select id="from_program_id" name="from_program_id" required><option value="">選択</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(old('from_program_id') == $program->id)>{{ $program->name }}</option>@endforeach</select></div><div class="field"><label for="to_program_id">交換先制度</label><select id="to_program_id" name="to_program_id" required><option value="">選択</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(old('to_program_id') == $program->id)>{{ $program->name }}</option>@endforeach</select></div><div class="field"><label for="name">交換関係名</label><input id="name" name="name" maxlength="200" value="{{ old('name') }}"></div></div>@endif</div>
<div class="card"><h2>交換条件</h2><div class="form-grid">@foreach(['from_quantity'=>'交換元の基準数量','to_quantity'=>'交換先の基準数量','minimum_from_quantity'=>'最低交換量','increment_from_quantity'=>'交換単位','maximum_from_quantity'=>'最大交換量','fee_quantity'=>'手数料数量'] as $field=>$label)<div class="field"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" min="{{ in_array($field, ['from_quantity','increment_from_quantity']) ? '0.0001' : '0' }}" step="0.0001" value="{{ old($field, $base->$field) }}" @required(in_array($field, ['from_quantity','to_quantity']))></div>@endforeach<div class="field"><label for="fee_program_id">手数料制度</label><select id="fee_program_id" name="fee_program_id"><option value="">なし</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(old('fee_program_id', $base->fee_program_id) == $program->id)>{{ $program->name }}</option>@endforeach</select></div><div class="field"><label for="estimated_days_min">最短日数</label><input id="estimated_days_min" name="estimated_days_min" type="number" min="0" value="{{ old('estimated_days_min', $base->estimated_days_min) }}"></div><div class="field"><label for="estimated_days_max">最長日数</label><input id="estimated_days_max" name="estimated_days_max" type="number" min="0" value="{{ old('estimated_days_max', $base->estimated_days_max) }}"></div><div class="field"><label for="duration_text">所要時間の説明</label><input id="duration_text" name="duration_text" maxlength="150" value="{{ old('duration_text', $base->duration_text) }}" placeholder="例: 月末締め翌月19日頃"></div></div></div>
<div class="card"><h2>期間・キャンペーン</h2><div class="form-grid"><div class="field"><label for="valid_from">有効開始日</label><input id="valid_from" name="valid_from" type="date" value="{{ old('valid_from', $base->valid_from) }}"></div><div class="field"><label for="valid_to">有効終了日</label><input id="valid_to" name="valid_to" type="date" value="{{ old('valid_to', $base->valid_to) }}"></div><div class="field"><label for="campaign_name">キャンペーン名</label><input id="campaign_name" name="campaign_name" maxlength="255" value="{{ old('campaign_name', $base->campaign_name) }}"></div></div><label><input type="checkbox" name="campaign_only" value="1" @checked(old('campaign_only', $base->campaign_only))> キャンペーン限定</label><p class="muted">期間未設定のキャンペーンは現在使える候補に出しません。</p></div>
<div class="card"><h2>条件と手順</h2><div class="field"><label for="conditions_text">条件</label><textarea id="conditions_text" name="conditions_text">{{ old('conditions_text', $base->conditions_text) }}</textarea></div><div class="field"><label for="instructions">交換手順</label><textarea id="instructions" name="instructions">{{ old('instructions', $base->instructions) }}</textarea></div><div class="field"><label for="official_url">公式 URL</label><input id="official_url" name="official_url" type="url" value="{{ old('official_url', $base->official_url) }}"></div><div class="field"><label for="notes">メモ</label><textarea id="notes" name="notes">{{ old('notes', $base->notes) }}</textarea></div></div>
<label><input type="checkbox" name="active" value="1" @checked(old('active', $base->exists ? $base->active : true))> 現在の候補に表示</label>@if($base->exists)<label><input type="checkbox" name="deactivate_previous" value="1"> 旧バージョンを候補から外す</label>@endif<div><button>{{ $base->exists ? '新しい版を保存' : 'ルールを登録' }}</button></div></form>
@endsection
