@extends('layouts.app')
@section('title', $rule->fromProgram->name.' → '.$rule->toProgram->name)
@section('content')
<div class="crumb"><a href="{{ route('conversion.rules.index') }}">交換ルール</a> / 詳細</div><div class="page-head"><div><h1>{{ $rule->fromProgram->name }} → {{ $rule->toProgram->name }}</h1><p class="muted">Version {{ $rule->version_no }} · {{ $rule->campaign_only ? 'キャンペーン' : '通常' }} · {{ $current ? '現在使える' : '現在使えない' }}</p></div><a class="button" href="{{ route('conversion.rules.new-version', $rule) }}">新しい版を作成</a></div>
@if($usedCount)<div class="warning">このルールは {{ $usedCount }} 件の移行で使用されています。条件変更は新しい版で登録してください。</div>@endif
@if($overlapCount)<div class="help">同じ交換関係に期間が重なるルールが {{ $overlapCount }} 件あります。通常とキャンペーンの条件を確認してください。</div>@endif
<div class="card"><h2>交換条件</h2><dl class="detail-grid"><div><dt>基準数量</dt><dd>{{ $rule->from_quantity }} {{ $rule->fromProgram->unit_name }} → {{ $rule->to_quantity }} {{ $rule->toProgram->unit_name }}</dd></div><div><dt>表示用比率</dt><dd>{{ \Brick\Math\BigDecimal::of($rule->to_quantity)->dividedBy($rule->from_quantity, 6, \Brick\Math\RoundingMode::DOWN)->multipliedBy(100) }}%</dd></div><div><dt>最低量</dt><dd>{{ $rule->minimum_from_quantity ?? '—' }}</dd></div><div><dt>交換単位</dt><dd>{{ $rule->increment_from_quantity ?? '—' }}</dd></div><div><dt>最大量</dt><dd>{{ $rule->maximum_from_quantity ?? '—' }}</dd></div><div><dt>手数料</dt><dd>{{ $rule->fee_quantity ?? '—' }} @if($rule->fee_program_id){{ \App\Models\BenefitProgram::query()->find($rule->fee_program_id)?->unit_name }}@endif</dd></div><div><dt>所要時間</dt><dd>{{ $rule->duration_text ?: '—' }} @if($rule->estimated_days_max !== null)（最長 {{ $rule->estimated_days_max }} 日）@endif</dd></div><div><dt>有効期間</dt><dd>{{ $rule->valid_from ?: '指定なし' }} 〜 {{ $rule->valid_to ?: '指定なし' }}</dd></div><div><dt>キャンペーン</dt><dd>{{ $rule->campaign_name ?: '—' }}</dd></div><div><dt>候補設定</dt><dd>{{ $rule->active ? '有効' : '無効' }}</dd></div></dl>@if($rule->conditions_text)<p><strong>条件</strong><br>{{ $rule->conditions_text }}</p>@endif</div>
<div class="card"><h2>表示情報を修正</h2><form class="stack" method="post" action="{{ route('conversion.rules.notes', $rule) }}">@csrf<div class="field"><label for="instructions">手順</label><textarea id="instructions" name="instructions">{{ old('instructions', $rule->instructions) }}</textarea></div><div class="field"><label for="official_url">公式 URL</label><input id="official_url" name="official_url" type="url" value="{{ old('official_url', $rule->official_url) }}"></div><div class="field"><label for="notes">メモ</label><textarea id="notes" name="notes">{{ old('notes', $rule->notes) }}</textarea></div><div class="row"><button class="secondary">表示情報を保存</button>@if($rule->official_url)<a href="{{ $rule->official_url }}" target="_blank" rel="noopener noreferrer">公式ページを開く</a>@endif</div></form></div>
<div class="card"><h2>同じ交換関係の版</h2><div class="list">@foreach($rule->group->rules->sortByDesc('version_no') as $version)<div class="list-item"><a href="{{ route('conversion.rules.show', $version) }}">Version {{ $version->version_no }} · {{ $version->from_quantity }} → {{ $version->to_quantity }} @if($version->campaign_only)· キャンペーン@endif</a><span>{{ $version->active ? '有効設定' : '無効設定' }}</span></div>@endforeach</div></div>
@if($rule->active)<form method="post" action="{{ route('conversion.rules.deactivate', $rule) }}" onsubmit="return confirm('現在の候補から外しますか？ 過去の移行履歴は残ります。')">@csrf<button class="danger">候補から外す</button></form>@endif
@endsection
