@extends('layouts.app')
@section('title', '横断検索')
@section('content')
<h1>横断検索</h1>
<div class="row">@foreach(['urgent'=>'今すぐ対応','expiry7'=>'期限7日以内','expiry30'=>'期限30日以内','undecided'=>'方針未設定','sell_unlisted'=>'売る予定・未出品','listed_expiring'=>'出品中・期限接近','overdue'=>'移行予定日超過'] as $key => $label)<a class="button secondary" href="{{ route('search.index', ['preset' => $key]) }}">{{ $label }}</a>@endforeach</div>
<form method="get" action="{{ route('search.index') }}" class="card">
 @if(!empty($filters['preset']))<input type="hidden" name="preset" value="{{ $filters['preset'] }}">@endif
 <div class="field"><label for="q">キーワード</label><input id="q" name="q" type="search" value="{{ $filters['q'] ?? '' }}" placeholder="制度・ロット・取引など"></div>
 <div class="field"><label for="member">名義</label><select id="member" name="member"><option value="">すべて</option><option value="shared" @selected(($filters['member'] ?? '') === 'shared')>家族共通</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected(($filters['member'] ?? '') == $member->id)>{{ $member->display_name }}</option>@endforeach</select></div>
 <div class="field"><label for="category">カテゴリ</label><select id="category" name="category"><option value="">すべて</option>@foreach(['point','mile','e_money','gift','shareholder_benefit','coupon','discount','campaign','other'] as $category)<option value="{{ $category }}" @selected(($filters['category'] ?? '') === $category)>{{ $category }}</option>@endforeach</select></div>
 <div class="field"><label for="program">制度</label><select id="program" name="program"><option value="">すべて</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(($filters['program'] ?? '') == $program->id)>{{ $program->name }}</option>@endforeach</select></div>
 <div class="field"><label for="policy">方針</label><select id="policy" name="policy"><option value="">すべて</option>@foreach(['self_use'=>'自分で使う','sell_now'=>'今売る','hold'=>'保留','bundle'=>'まとめる','do_not_sell'=>'売らない','transfer_to_points'=>'ポイントへ移行','undecided'=>'未設定'] as $value => $label)<option value="{{ $value }}" @selected(($filters['policy'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
 <div class="field"><label for="expires_within">期限</label><select id="expires_within" name="expires_within"><option value="">すべて</option>@foreach(['0'=>'本日','3'=>'3日以内','7'=>'7日以内','14'=>'14日以内','30'=>'30日以内','90'=>'90日以内','expired'=>'期限切れ','none'=>'期限なし'] as $value => $label)<option value="{{ $value }}" @selected(($filters['expires_within'] ?? '') === (string) $value)>{{ $label }}</option>@endforeach</select></div>
 <div class="field"><label for="listing">出品</label><select id="listing" name="listing"><option value="">すべて</option>@foreach(['unlisted'=>'未出品','draft'=>'下書きあり','listed'=>'出品中','partial'=>'一部出品中','ended_unsold'=>'売れず終了','sold'=>'売却済み','cancelled'=>'取消済み'] as $value => $label)<option value="{{ $value }}" @selected(($filters['listing'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
 <div class="field"><label for="transfer_status">移行状態</label><select id="transfer_status" name="transfer_status"><option value="">すべて</option>@foreach(['planned'=>'予定','processing'=>'移行中','overdue'=>'予定日超過','completed'=>'完了','error'=>'エラー'] as $value => $label)<option value="{{ $value }}" @selected(($filters['transfer_status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
 <div class="field"><label for="restriction">譲渡制限</label><select id="restriction" name="restriction"><option value="">すべて</option><option value="none" @selected(($filters['restriction'] ?? '') === 'none')>未設定</option><option value="non_transferable" @selected(($filters['restriction'] ?? '') === 'non_transferable')>譲渡・転売不可</option><option value="transferable" @selected(($filters['restriction'] ?? '') === 'transferable')>譲渡可</option></select></div>
 <div class="field"><label><input type="checkbox" name="active_only" value="1" @checked(!empty($filters['active_only']))> 有効な口座・制度のみ</label></div>
 <div class="field"><label for="sort">並び順</label><select id="sort" name="sort"><option value="expiry" @selected(($filters['sort'] ?? 'expiry') === 'expiry')>期限が近い順</option><option value="name" @selected(($filters['sort'] ?? '') === 'name')>特典名順</option><option value="updated" @selected(($filters['sort'] ?? '') === 'updated')>更新が新しい順</option></select></div>
 <div class="field"><label for="per_page">表示件数</label><select id="per_page" name="per_page">@foreach([25,50,100] as $count)<option value="{{ $count }}" @selected(($filters['per_page'] ?? 25) == $count)>{{ $count }}</option>@endforeach</select></div>
 <button>検索</button> <a class="button secondary" href="{{ route('search.index') }}">条件を解除</a>
</form>
@if($filters)<div class="row" aria-label="適用中の条件">@foreach($filters as $key => $value)@if($value !== null && $value !== '')<a class="button secondary" href="{{ route('search.index', request()->except($key)) }}">{{ $key }}: {{ $value }} ×</a>@endif @endforeach</div>@endif
<section class="card"><h2>保有ロット {{ $results['lots']->total() }}件</h2><div class="list">@forelse($results['lots'] as $lot)<a class="list-item" href="{{ route('ledger.lots.show', $lot) }}"><span><strong>{{ $lot->display_name ?: $lot->account->program->name }}</strong><small>{{ $lot->account->householdMember?->display_name ?: '家族共通' }} · {{ $lot->account->program->name }} · 方針 {{ $lot->action_policy }} · 期限 {{ $lot->expires_at ?: 'なし' }}</small><small>出品中 {{ $lot->listed_quantity }}</small></span><strong>{{ $lot->remaining }} {{ $lot->account->program->unit_name }}</strong></a>@empty<p>条件に一致するロットはありません。</p>@endforelse</div>{{ $results['lots']->links() }}</section>
<section class="card"><h2>ロットなし残高 {{ $results['accounts']->total() }}件</h2><div class="list">@forelse($results['accounts'] as $account)<a class="list-item" href="{{ route('ledger.accounts.transactions', $account) }}"><span><strong>{{ $account->program->name }}</strong><small>{{ $account->householdMember?->display_name ?: '家族共通' }} · {{ $account->account_label }}</small></span><strong>{{ $account->plain_balance }} {{ $account->program->unit_name }}</strong></a>@empty<p>条件に一致する口座残高はありません。</p>@endforelse</div>{{ $results['accounts']->links() }}</section>
@if(filled($filters['q'] ?? null) || filled($filters['transfer_status'] ?? null) || ($filters['preset'] ?? null) === 'overdue')
@foreach(['transactions'=>'取引','listings'=>'出品','transfers'=>'移行','rules'=>'交換ルール'] as $type => $label)<section class="card"><h2>{{ $label }}</h2><div class="list">@forelse($results['extra'][$type] as $item)@php($url = match($type) {'transactions' => route('ledger.transactions.show', $item), 'listings' => route('listings.show', $item), 'transfers' => route('transfers.show', $item), 'rules' => route('conversion.rules.show', $item)})<a class="list-item" href="{{ $url }}"><span>{{ match($type) {'transactions' => $item->merchant_or_purpose ?: $item->account->program->name, 'listings' => $item->title ?: $item->marketplace, 'transfers' => $item->name ?: $item->purpose, 'rules' => $item->fromProgram->name.' → '.$item->toProgram->name} }}</span><small>#{{ $item->id }}</small></a>@empty<p>一致する{{ $label }}はありません。</p>@endforelse</div></section>@endforeach
@endif
@endsection
