<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BenefitAccountController;
use App\Http\Controllers\BenefitDashboardController;
use App\Http\Controllers\BenefitLedgerController;
use App\Http\Controllers\BenefitListingController;
use App\Http\Controllers\BenefitLotController;
use App\Http\Controllers\BenefitNotificationController;
use App\Http\Controllers\BenefitProgramController;
use App\Http\Controllers\BenefitSearchController;
use App\Http\Controllers\BenefitTransactionController;
use App\Http\Controllers\BenefitTransferController;
use App\Http\Controllers\ConversionRouteController;
use App\Http\Controllers\ConversionRuleController;
use App\Http\Controllers\ConversionTransferDraftController;
use App\Http\Controllers\ExcelImportController;
use App\Http\Controllers\HouseholdMemberController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect()->route('dashboard.index'));

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:5,1')->name('login.submit');
});

Route::middleware('auth')->group(function (): void {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/dashboard', [BenefitDashboardController::class, 'index'])->name('dashboard.index');
    Route::get('/search', [BenefitSearchController::class, 'index'])->name('search.index');
    Route::get('/notifications', [BenefitNotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/read-all', [BenefitNotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::get('/notifications/preferences', [BenefitNotificationController::class, 'preferences'])->name('notifications.preferences');
    Route::post('/notifications/preferences', [BenefitNotificationController::class, 'updatePreferences'])->name('notifications.preferences.update');
    Route::post('/notifications/{notification}/open', [BenefitNotificationController::class, 'open'])->name('notifications.open');
    Route::post('/notifications/{notification}/dismiss', [BenefitNotificationController::class, 'dismiss'])->name('notifications.dismiss');
    Route::get('/imports/excel', [ExcelImportController::class, 'index'])->name('imports.index');
    Route::post('/imports/excel', [ExcelImportController::class, 'upload'])->name('imports.upload');
    Route::get('/imports/excel/{batch}', [ExcelImportController::class, 'show'])->name('imports.show');
    Route::post('/imports/excel/{batch}/configure', [ExcelImportController::class, 'configure'])->name('imports.configure');
    Route::post('/imports/excel/{batch}/execute', [ExcelImportController::class, 'execute'])->name('imports.execute');
    Route::post('/imports/excel/{batch}/records/{record}', [ExcelImportController::class, 'override'])->name('imports.records.override');
    Route::post('/dashboard/lots/{lot}/policy', [BenefitDashboardController::class, 'updatePolicy'])->name('dashboard.lots.policy');
    Route::get('/benefits', [BenefitLedgerController::class, 'index'])->name('ledger.home');
    Route::get('/transactions', [BenefitTransactionController::class, 'index'])->name('ledger.transactions.index');
    Route::get('/transactions/create', [BenefitTransactionController::class, 'create'])->name('ledger.transactions.create');
    Route::post('/transactions', [BenefitTransactionController::class, 'store'])->name('ledger.transactions.store');
    Route::get('/transactions/{transaction}', [BenefitTransactionController::class, 'show'])->name('ledger.transactions.show');
    Route::post('/transactions/{transaction}/reverse', [BenefitTransactionController::class, 'reverse'])->name('ledger.transactions.reverse');
    Route::get('/benefit-accounts/{account}/transactions', [BenefitTransactionController::class, 'account'])->name('ledger.accounts.transactions');
    Route::get('/benefit-accounts/{account}/use', [BenefitTransactionController::class, 'useForm'])->name('ledger.accounts.use');
    Route::post('/benefit-accounts/{account}/use', [BenefitTransactionController::class, 'allocateUse'])->name('ledger.accounts.use.store');
    Route::get('/lots', [BenefitLotController::class, 'index'])->name('ledger.lots.index');
    Route::get('/lots/create', [BenefitLotController::class, 'create'])->name('ledger.lots.create');
    Route::post('/lots', [BenefitLotController::class, 'store'])->name('ledger.lots.store');
    Route::get('/lots/{lot}', [BenefitLotController::class, 'show'])->name('ledger.lots.show');
    Route::get('/lots/{lot}/edit', [BenefitLotController::class, 'edit'])->name('ledger.lots.edit');
    Route::put('/lots/{lot}', [BenefitLotController::class, 'update'])->name('ledger.lots.update');
    Route::post('/lots/{lot}/use', [BenefitLotController::class, 'use'])->name('ledger.lots.use');
    Route::post('/lots/{lot}/expire', [BenefitLotController::class, 'expire'])->name('ledger.lots.expire');
    Route::post('/lots/{lot}/cancel', [BenefitLotController::class, 'cancel'])->name('ledger.lots.cancel');
    Route::get('/listings', [BenefitListingController::class, 'index'])->name('listings.index');
    Route::get('/listings/create', [BenefitListingController::class, 'create'])->name('listings.create');
    Route::post('/listings', [BenefitListingController::class, 'store'])->name('listings.store');
    Route::get('/listings/{listing}', [BenefitListingController::class, 'show'])->name('listings.show');
    Route::get('/listings/{listing}/edit', [BenefitListingController::class, 'edit'])->name('listings.edit');
    Route::put('/listings/{listing}', [BenefitListingController::class, 'update'])->name('listings.update');
    Route::post('/listings/{listing}/publish', [BenefitListingController::class, 'publish'])->name('listings.publish');
    Route::post('/listings/{listing}/price', [BenefitListingController::class, 'changePrice'])->name('listings.price');
    Route::post('/listings/{listing}/cancel', [BenefitListingController::class, 'cancel'])->name('listings.cancel');
    Route::post('/listings/{listing}/end-unsold', [BenefitListingController::class, 'endUnsold'])->name('listings.end-unsold');
    Route::post('/listings/{listing}/relist', [BenefitListingController::class, 'relist'])->name('listings.relist');
    Route::get('/listings/{listing}/sell', [BenefitListingController::class, 'sellForm'])->name('listings.sell.form');
    Route::post('/listings/{listing}/sell', [BenefitListingController::class, 'sell'])->name('listings.sell');
    Route::post('/listings/{listing}/reverse-sale', [BenefitListingController::class, 'reverseSale'])->name('listings.reverse-sale');
    Route::get('/transfers', [BenefitTransferController::class, 'index'])->name('transfers.index');
    Route::get('/transfers/create', [BenefitTransferController::class, 'create'])->name('transfers.create');
    Route::post('/transfers', [BenefitTransferController::class, 'store'])->name('transfers.store');
    Route::get('/transfers/{group}', [BenefitTransferController::class, 'show'])->name('transfers.show');
    Route::get('/transfers/{group}/steps/create', [BenefitTransferController::class, 'stepCreate'])->name('transfers.steps.create');
    Route::post('/transfers/{group}/steps', [BenefitTransferController::class, 'addStep'])->name('transfers.steps.store');
    Route::post('/transfer-steps/{step}/start', [BenefitTransferController::class, 'start'])->name('transfers.steps.start');
    Route::get('/transfer-steps/{step}/complete', [BenefitTransferController::class, 'completeForm'])->name('transfers.steps.complete.form');
    Route::post('/transfer-steps/{step}/complete', [BenefitTransferController::class, 'complete'])->name('transfers.steps.complete');
    Route::post('/transfer-steps/{step}/cancel', [BenefitTransferController::class, 'cancelPlanned'])->name('transfers.steps.cancel');
    Route::post('/transfer-steps/{step}/refund', [BenefitTransferController::class, 'cancelWithRefund'])->name('transfers.steps.refund');
    Route::post('/transfer-steps/{step}/error', [BenefitTransferController::class, 'markError'])->name('transfers.steps.error');
    Route::post('/transfer-steps/{step}/expected-date', [BenefitTransferController::class, 'updateExpectedDate'])->name('transfers.steps.expected-date');
    Route::get('/conversion-rules', [ConversionRuleController::class, 'index'])->name('conversion.rules.index');
    Route::get('/conversion-rules/create', [ConversionRuleController::class, 'create'])->name('conversion.rules.create');
    Route::post('/conversion-rules', [ConversionRuleController::class, 'store'])->name('conversion.rules.store');
    Route::get('/conversion-rules/{rule}', [ConversionRuleController::class, 'show'])->name('conversion.rules.show');
    Route::get('/conversion-rules/{rule}/new-version', [ConversionRuleController::class, 'newVersion'])->name('conversion.rules.new-version');
    Route::post('/conversion-rules/{rule}/versions', [ConversionRuleController::class, 'storeVersion'])->name('conversion.rules.versions.store');
    Route::post('/conversion-rules/{rule}/notes', [ConversionRuleController::class, 'updateNotes'])->name('conversion.rules.notes');
    Route::post('/conversion-rules/{rule}/deactivate', [ConversionRuleController::class, 'deactivate'])->name('conversion.rules.deactivate');
    Route::get('/conversion-routes', [ConversionRouteController::class, 'index'])->name('conversion.routes.index');
    Route::get('/conversion-routes/create', [ConversionRouteController::class, 'create'])->name('conversion.routes.create');
    Route::post('/conversion-routes', [ConversionRouteController::class, 'store'])->name('conversion.routes.store');
    Route::get('/conversion-routes/{route}', [ConversionRouteController::class, 'show'])->name('conversion.routes.show');
    Route::get('/conversion-routes/{route}/transfer-draft', [ConversionTransferDraftController::class, 'create'])->name('conversion.routes.draft');
    Route::post('/conversion-routes/{route}/transfer-draft/preview', [ConversionTransferDraftController::class, 'preview'])->name('conversion.routes.draft.preview');
    Route::post('/conversion-routes/{route}/transfer-draft', [ConversionTransferDraftController::class, 'store'])->name('conversion.routes.draft.store');
    Route::post('/conversion-routes/{route}/deactivate', [ConversionRouteController::class, 'deactivate'])->name('conversion.routes.deactivate');
    Route::view('/settings/benefits', 'settings.home')->name('settings.home');

    Route::get('/settings/household-members', [HouseholdMemberController::class, 'index'])->name('settings.members.index');
    Route::get('/settings/household-members/create', [HouseholdMemberController::class, 'create'])->name('settings.members.create');
    Route::post('/settings/household-members', [HouseholdMemberController::class, 'store'])->name('settings.members.store');
    Route::get('/settings/household-members/{member}/edit', [HouseholdMemberController::class, 'edit'])->name('settings.members.edit');
    Route::put('/settings/household-members/{member}', [HouseholdMemberController::class, 'update'])->name('settings.members.update');
    Route::post('/settings/household-members/{member}/toggle', [HouseholdMemberController::class, 'toggle'])->name('settings.members.toggle');

    Route::get('/settings/benefit-programs', [BenefitProgramController::class, 'index'])->name('settings.programs.index');
    Route::get('/settings/benefit-programs/create', [BenefitProgramController::class, 'create'])->name('settings.programs.create');
    Route::post('/settings/benefit-programs', [BenefitProgramController::class, 'store'])->name('settings.programs.store');
    Route::get('/settings/benefit-programs/{program}', [BenefitProgramController::class, 'show'])->name('settings.programs.show');
    Route::get('/settings/benefit-programs/{program}/edit', [BenefitProgramController::class, 'edit'])->name('settings.programs.edit');
    Route::put('/settings/benefit-programs/{program}', [BenefitProgramController::class, 'update'])->name('settings.programs.update');
    Route::post('/settings/benefit-programs/{program}/toggle', [BenefitProgramController::class, 'toggle'])->name('settings.programs.toggle');
    Route::post('/settings/benefit-programs/{program}/aliases', [BenefitProgramController::class, 'addAlias'])->name('settings.programs.aliases.store');
    Route::delete('/settings/benefit-programs/{program}/aliases/{alias}', [BenefitProgramController::class, 'removeAlias'])->name('settings.programs.aliases.destroy');

    Route::get('/settings/benefit-accounts', [BenefitAccountController::class, 'index'])->name('settings.accounts.index');
    Route::get('/settings/benefit-accounts/create', [BenefitAccountController::class, 'create'])->name('settings.accounts.create');
    Route::post('/settings/benefit-accounts', [BenefitAccountController::class, 'store'])->name('settings.accounts.store');
    Route::get('/settings/benefit-accounts/{account}', [BenefitAccountController::class, 'show'])->name('settings.accounts.show');
    Route::get('/settings/benefit-accounts/{account}/edit', [BenefitAccountController::class, 'edit'])->name('settings.accounts.edit');
    Route::put('/settings/benefit-accounts/{account}', [BenefitAccountController::class, 'update'])->name('settings.accounts.update');
    Route::post('/settings/benefit-accounts/{account}/toggle', [BenefitAccountController::class, 'toggle'])->name('settings.accounts.toggle');
});
