@extends('layouts.app')
@section('title', $route->name)
@section('content')
<div class="crumb"><a href="{{ route('conversion.routes.index') }}">交換ルート</a> / 詳細</div><div class="page-head"><div><h1>{{ $route->name }}</h1><p class="muted">{{ $route->active ? '有効設定' : '無効設定' }} · {{ $usable ? '現在利用可能' : '条件を確認してください' }}</p></div><a class="button secondary" href="{{ route('conversion.rules.index') }}">交換ルール</a></div>
@if($route->description)<div class="card"><p>{{ $route->description }}</p></div>@endif
@if($route->active)<p><a class="button" href="{{ route('conversion.routes.draft', $route) }}">このルートで移行を作成</a></p>@endif
@foreach($steps as $step)<article class="card"><h2>Step {{ $step->sequence_no }} · {{ $step->ruleGroup->fromProgram->name }} → {{ $step->ruleGroup->toProgram->name }}</h2>@php($rule = $resolved[$step->id]['rule'])@if($rule)<p><a href="{{ route('conversion.rules.show', $rule) }}">Version {{ $rule->version_no }}</a> · {{ $rule->from_quantity }} → {{ $rule->to_quantity }} · 最低 {{ $rule->minimum_from_quantity ?? '—' }} · 単位 {{ $rule->increment_from_quantity ?? '—' }} · 所要 {{ $rule->duration_text ?: ($rule->estimated_days_max === null ? '未設定' : $rule->estimated_days_max.'日以内') }}</p>@if($rule->campaign_only)<p class="warning">キャンペーン: {{ $rule->campaign_name ?: '期間限定' }} · {{ $rule->valid_from ?: '未設定' }} 〜 {{ $rule->valid_to ?: '未設定' }}</p>@endif @if($rule->instructions)<p><strong>手順</strong><br>{{ $rule->instructions }}</p>@endif @if($rule->official_url)<p><a href="{{ $rule->official_url }}" target="_blank" rel="noopener noreferrer">公式ページを開く</a></p>@endif @else<p class="warning">現在有効なルールを一意に選べません。優先ルールや期間を確認してください。</p>@endif @if($step->preferred_rule_id && !$resolved[$step->id]['candidates']->contains('id', $step->preferred_rule_id))<p class="help">優先ルール Version {{ $step->preferredRule?->version_no }} は現在無効です。代替候補があれば自動表示しています。</p>@endif</article>@endforeach
<div class="card"><h2>数量をシミュレーション</h2><form class="row" method="get"><div class="field"><label for="quantity">最初の制度の数量</label><input id="quantity" name="quantity" type="number" min="0.0001" step="0.0001" value="{{ $input['quantity'] ?? '' }}" required></div><button class="secondary">概算する</button></form><p class="muted">各制度のネイティブ数量で計算します。手数料や複雑な条件がある場合は概算を止めます。</p></div>
@if($simulation)<div class="card"><h2>概算結果</h2><div class="list">@foreach($simulation['rows'] as $row)<div class="list-item"><div><strong>{{ $row['step']->ruleGroup->fromProgram->name }} → {{ $row['step']->ruleGroup->toProgram->name }}</strong><small>利用可能 {{ $row['available'] }} · 投入 {{ $row['used'] ?? '—' }} · 端数残り {{ $row['remaining'] ?? '—' }}</small>@if($row['reason'])<small>{{ $row['reason'] }}</small>@endif</div><strong>受取 {{ $row['received'] ?? '—' }}</strong></div>@endforeach</div>@if($simulation['completed'])<p><strong>最終受取の概算: {{ $simulation['destination_quantity'] }} {{ $steps->last()?->ruleGroup->toProgram->unit_name }}</strong></p>@else<p class="warning">条件により変動します。</p>@endif @if($simulation['estimated_days_max'] !== null && $simulation['completed'])<p class="help">所要時間の参考: 最大 {{ $simulation['estimated_days_max'] }} 日の合計。最短保証ではありません。</p>@endif</div>@endif
@if($route->active)<form method="post" action="{{ route('conversion.routes.deactivate', $route) }}" onsubmit="return confirm('このルートを候補から外しますか？')">@csrf<button class="danger">候補から外す</button></form>@endif
@endsection
